# Frame-by-frame digest of every NN-*.txt.body capture, as Markdown on stdout.
# Reads raw bytes only; the verbatim captures stay the source of truth.
import glob
import json
import os

HERE = os.path.dirname(os.path.abspath(__file__))


def status(txt_path):
    with open(txt_path, encoding="utf-8", errors="replace") as f:
        for line in f:
            if line.startswith("HTTP/"):
                return line.strip()
    return "?"


def dechunk(raw):
    """Strip HTTP/1.1 chunk framing; return raw unchanged if it is not chunked."""
    out, i = b"", 0
    while True:
        j = raw.find(b"\r\n", i)
        if j < 0:
            return raw
        try:
            size = int(raw[i:j].split(b";")[0], 16)
        except ValueError:
            return raw
        if size == 0:
            return out
        out += raw[j + 2:j + 2 + size]
        i = j + 2 + size + 2


def delta_keys(ch):
    d = ch.get("delta") or ch.get("message") or {}
    return sorted(k for k, v in d.items() if v not in (None, "", []))


def frame_row(i, obj):
    ch = obj.get("choices") or []
    c0 = ch[0] if ch else {}
    tc = (c0.get("delta") or c0.get("message") or {}).get("tool_calls") or []
    tcs = ";".join(f"idx={t.get('index')} id={t.get('id')} name={(t.get('function') or {}).get('name')} "
                   f"args={json.dumps((t.get('function') or {}).get('arguments'))}" for t in tc)
    return (f"| {i} | {obj.get('model')} | {obj.get('provider')} | {len(ch)} | {','.join(delta_keys(c0))} | "
            f"{c0.get('finish_reason')} | {c0.get('native_finish_reason')} | {'usage' in obj} | "
            f"{'error' in obj} | {tcs} |")


print("# Frame digest (generated by summarize.py)\n")
for body in sorted(glob.glob(os.path.join(HERE, "[0-9][0-9]-*.txt.body"))):
    name = os.path.basename(body)[:-9]
    raw = open(body, "rb").read()
    print(f"## {name}\n\n{status(body[:-5])}, {len(raw)} bytes as received (curl --raw keeps chunk framing)\n")
    text = dechunk(raw).decode("utf-8", errors="replace")
    if not text.lstrip().startswith((":", "data:")):
        try:
            obj = json.loads(text)
            print("Non-SSE JSON. Top-level keys:", sorted(obj))
            if "usage" in obj:
                print("\nusage:", json.dumps(obj["usage"]))
            print("\n| # | model | provider | choices | message keys | finish | native_finish | usage | error | tool_calls |")
            print("|---|---|---|---|---|---|---|---|---|---|")
            print(frame_row(0, obj))
        except ValueError:
            print("Not JSON, not SSE.")
        print()
        continue
    lines = text.split("\n")
    comments = [l for l in lines if l.startswith(":")]
    other = [l for l in lines if l and not l.startswith((":", "data:"))]
    print(f"SSE comment lines: {len(comments)} distinct {sorted(set(comments))}; non-data non-comment lines: {other[:5]}\n")
    print("| # | model | provider | choices | delta keys | finish | native_finish | usage | error | tool_calls |")
    print("|---|---|---|---|---|---|---|---|---|---|")
    seen_done = False
    after_done = []
    i = 0
    usages = []
    for l in lines:
        if not l.startswith("data:"):
            if seen_done and l.strip():
                after_done.append(l)
            continue
        payload = l[5:].strip()
        if seen_done:
            after_done.append(l)
        if payload == "[DONE]":
            seen_done = True
            print(f"| {i} | [DONE] |||||||||")
            i += 1
            continue
        try:
            obj = json.loads(payload)
        except ValueError:
            print(f"| {i} | unparsable: {payload[:60]} |||||||||")
            i += 1
            continue
        if "usage" in obj:
            usages.append(obj["usage"])
        print(frame_row(i, obj))
        i += 1
    print(f"\n[DONE] seen: {seen_done}; lines after [DONE]: {after_done}\n")
    for u in usages:
        print("usage:", json.dumps(u), "\n")
